// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyBpIh67xOZXLj5Bw9jMEqnFIh85e42Il1E",
  authDomain: "edutrack-73a2e.firebaseapp.com",
  projectId: "edutrack-73a2e",
  storageBucket: "edutrack-73a2e.firebasestorage.app",
  messagingSenderId: "656920649358",
  appId: "1:656920649358:web:1bc12a4de738b0eeb1b3df",
  measurementId: "G-D1G98D7XC9",
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyBSS2VH-mnxd0WqdAp13WhyBNwcyn6674Q',
  appId: '1:656920649358:android:bb9ea547cd1dd9a0b1b3df',
  messagingSenderId: '656920649358',
  projectId: 'edutrack-73a2e',
  databaseURL: 'https://edutrack-73a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'edutrack-73a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNzlDRENSDhg8uxGY6O0p4NAw5nwMQkQ',
    appId: '1:656920649358:ios:33c3b2c74a4a02ecb1b3df',
    messagingSenderId: '656920649358',
    projectId: 'edutrack-73a2e',
    databaseURL: 'https://edutrack-73a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-73a2e.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKNzlDRENSDhg8uxGY6O0p4NAw5nwMQkQ',
    appId: '1:656920649358:ios:33c3b2c74a4a02ecb1b3df',
    messagingSenderId: '656920649358',
    projectId: 'edutrack-73a2e',
    databaseURL: 'https://edutrack-73a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-73a2e.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
  apiKey: 'AIzaSyBSS2VH-mnxd0WqdAp13WhyBNwcyn6674Q',
  appId: '1:656920649358:web:bb9ea547cd1dd9a0b1b3df',
  messagingSenderId: '656920649358',
  projectId: 'edutrack-73a2e',
  authDomain: 'edutrack-73a2e.firebaseapp.com',
  databaseURL: 'https://edutrack-73a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'edutrack-73a2e.firebasestorage.app',
  );
}
