// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGsVsXJ60eJsINtgCWWm3PbA5HHu4Xdzs',
    appId: '1:741991548014:web:037aea02350fe44969127f',
    messagingSenderId: '741991548014',
    projectId: 'edutrack-eb824',
    authDomain: 'edutrack-eb824.firebaseapp.com',
    databaseURL: 'https://edutrack-eb824-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-eb824.firebasestorage.app',
    measurementId: 'G-6Z3XMR0ZFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBr3XmwpgEouQxoVqD4DU2z1t_aDlU6E',
    appId: '1:741991548014:android:9c2465b08899a4f869127f',
    messagingSenderId: '741991548014',
    projectId: 'edutrack-eb824',
    databaseURL: 'https://edutrack-eb824-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-eb824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZwHn2yFJAqUXTXByVr_AH11cxbmEjkk',
    appId: '1:741991548014:ios:4e1370d3265f9d6b69127f',
    messagingSenderId: '741991548014',
    projectId: 'edutrack-eb824',
    databaseURL: 'https://edutrack-eb824-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-eb824.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZwHn2yFJAqUXTXByVr_AH11cxbmEjkk',
    appId: '1:741991548014:ios:4e1370d3265f9d6b69127f',
    messagingSenderId: '741991548014',
    projectId: 'edutrack-eb824',
    databaseURL: 'https://edutrack-eb824-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-eb824.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGsVsXJ60eJsINtgCWWm3PbA5HHu4Xdzs',
    appId: '1:741991548014:web:9da4a161ca973d0569127f',
    messagingSenderId: '741991548014',
    projectId: 'edutrack-eb824',
    authDomain: 'edutrack-eb824.firebaseapp.com',
    databaseURL: 'https://edutrack-eb824-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutrack-eb824.firebasestorage.app',
    measurementId: 'G-DQ22YZN1VR',
  );
}
